# Generated by Django 4.1.7 on 2023-03-10 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelData',
            fields=[
                ('ch_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ch_number', models.CharField(max_length=150)),
                ('plant_type', models.CharField(max_length=200)),
                ('plant_name', models.CharField(max_length=100)),
                ('last_water_added', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_type', models.CharField(max_length=200)),
                ('max_moisture_lvl', models.IntegerField(default=90)),
                ('min_moisture_lvl', models.IntegerField(default=40)),
                ('max_temperature_lvl', models.IntegerField(blank=True, null=True)),
                ('min_temperature_lvl', models.IntegerField(blank=True, null=True)),
                ('max_humidity_lvl', models.IntegerField(blank=True, null=True)),
                ('min_humidity_lvl', models.IntegerField(blank=True, null=True)),
                ('min_light_lvl', models.IntegerField(blank=True, null=True)),
                ('max_light_lvl', models.IntegerField(blank=True, null=True)),
                ('daylight_time', models.IntegerField(blank=True, null=True)),
                ('amount_water', models.IntegerField(blank=True, null=True)),
                ('hours_between_watering', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('plant_type', models.CharField(max_length=200)),
                ('moisture_lvl', models.IntegerField(blank=True, null=True)),
                ('temperature_lvl', models.IntegerField(blank=True, null=True)),
                ('humidity_lvl', models.IntegerField(blank=True, null=True)),
                ('light_lvl', models.IntegerField(blank=True, null=True)),
                ('water_added', models.BooleanField(default=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
